language: python
python:
  - "3.5"
  - "3.6"
addons:
  postgresql: "9.5"
services:
  - postgresql
env:
  matrix:
   - $DJANGO="Django>=2.0,<2.2"

install:
  - pip install -U pip
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install psycopg2cffi; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install psycopg2; fi
  - pip install -q "$DJANGO"
  - python setup.py develop

before_script:
  - psql -c 'create database dts_test_project;' -U postgres


script: ./run_tests.sh
