on:
  pull_request:
  push:
    branches: master

jobs:
  test_matrix:
    name: ${{ matrix.postgres-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6]
        postgres-version: [latest, 12, 11, 10, 9.6, 9.5]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        pip install psycopg2
        # always use latest Django here b/c the point is to test PostgreSQL compatibility
        pip install Django
        python setup.py develop

    - name: Create database
      run: |
        # maps the container port to localhost
        docker run --name db -p 5432:5432 -d postgres:${{ matrix.postgres-version }}

        psql -c 'create database dts_test_project;' -U postgres

    - name: Run tests
      run: |
        ./run_tests.sh

